### ISSUE TITLE
Easy Search

### ISSUE THREAD

**Issue by ghost1372** [crashh/Subtitle-Downloader#1]
hi why we can not  search easily?
just writing series/movies name and select which language is need,Finally all filtered subtitle list in grid and download it by selected it.

**Comment by crashh** [comment]
- Added tab where you can type in the information you want to search for.
- Added preferred language to setting tab.

I like the idea you suggest, and will add this to the new search tab, at some point.

**Comment by ghost1372** [comment]
Hello
thank you so much.
As you know, we have many translators, It is much better that the program allowed us to select subtitles for download.please work on this feature.
ver 2.0.1 is awsome i use every day.<3
