### ISSUE TITLE
Doesn't install, doesn't build.

### ISSUE THREAD

**Issue by sniper-developer** [crashh/Subtitle-Downloader#2]
1.Cannot be installed (log attached):
ERROR SUMMARY
    Below is a summary of the errors, details of these errors are listed later in the log.
    \* Activation of C:\Subtitle-Downloader-master\Lastest Build\SubtitleDownloader.application resulted in exception. Following failure messages were detected:
        + File, SubtitleDownloader.exe.config, has a different computed hash than specified in manifest.

[SUAWBLJ0.txt](https://github.com/crashh/Subtitle-Downloader/files/222412/SUAWBLJ0.txt)

2.Cannot be built:
Error       Unable to find manifest signing certificate in the certificate store.   SubtitleDownloaderV2    C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets 2883

**Comment by crashh** [comment]
Apparently GitHub messed with the exe file, changing the hash value. Fixed this by zipping the latest build.

In order to compile this yourself, you have to go into Project->Properties and remove the signing step. Will find a workaround for this later.

Lesson learned :-)
